/** メインプロセスの IPC 名と preload からの invoke で共用 */
export const SEISAN_CHANNELS = {
  db: {
    getPath: "seisan-db:getPath",
    selectFile: "seisan-db:selectFile",
    selectProjectFile: "seisan-db:selectProjectFile",
    createNew: "seisan-db:createNew",
    connect: "seisan-db:connect",
    status: "seisan-db:status",
  },
  project: {
    list: "seisan-project:list",
    get: "seisan-project:get",
    create: "seisan-project:create",
    update: "seisan-project:update",
    submit: "seisan-project:submit",
    approve: "seisan-project:approve",
    updateStatus: "seisan-project:updateStatus",
  },
  task: {
    listByProject: "seisan-task:listByProject",
    listAll: "seisan-task:listAll",
    create: "seisan-task:create",
    update: "seisan-task:update",
    updateDates: "seisan-task:updateDates",
    updateSort: "seisan-task:updateSort",
    updateStatus: "seisan-task:updateStatus",
    delete: "seisan-task:delete",
    initProjectTask: "seisan-task:initProjectTask",
    createFromDeadline: "seisan-task:createFromDeadline",
  },
  template: {
    list: "seisan-template:list",
    create: "seisan-template:create",
    update: "seisan-template:update",
    delete: "seisan-template:delete",
  },
  file: {
    listByProject: "seisan-file:listByProject",
    add: "seisan-file:add",
    open: "seisan-file:open",
    setObsolete: "seisan-file:setObsolete",
    readAsDataUrl: "seisan-file:readAsDataUrl",
    saveCopy: "seisan-file:saveCopy",
    downloadAll: "seisan-file:downloadAll",
    remove: "seisan-file:remove",
  },
  import: {
    downloadFormat: "seisan-import:downloadFormat",
    downloadCsvTemplate: "seisan-import:downloadCsvTemplate",
    selectCsv: "seisan-import:selectCsv",
    exportCsv: "seisan-import:exportCsv",
  },
  master: {
    status: "seisan-master:status",
    selectFile: "seisan-master:selectFile",
    disconnect: "seisan-master:disconnect",
    customers: "seisan-master:customers",
    models: "seisan-master:models",
    partNumbers: "seisan-master:partNumbers",
    componentNames: "seisan-master:componentNames",
    allModels: "seisan-master:allModels",
    allPartNumbers: "seisan-master:allPartNumbers",
    allComponentNames: "seisan-master:allComponentNames",
    groupNames: "seisan-master:groupNames",
    userNames: "seisan-master:userNames",
    distinctCompanies: "seisan-master:distinctCompanies",
    distinctGroups: "seisan-master:distinctGroups",
  },
  permission: {
    list: "seisan-permission:list",
    getRole: "seisan-permission:getRole",
    setRole: "seisan-permission:setRole",
    remove: "seisan-permission:remove",
  },
} as const;
